openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC Verifier API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
  /credentials/verify:
    post:
      summary: Verifies a verifiableCredential and returns a verificationResult in the response body.
      tags: 
       - Credentials
      operationId: verifyCredential
      description: Verifies a verifiableCredential and returns a verificationResult in the response body.
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyCredentialRequest"
        description: Parameters for verifying a verifiableCredential.
      responses:
        "200":
          description: Verifiable Credential successfully verified!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyCredentialResponse"
        "400":
          description: invalid input!
        "401":
          description: Missing or invalid auth credentials.
        "403":
          description: Incorrect scope or permissions.
        "500":
          description: error!
  /presentations/verify:
    post:
      summary: Verifies a Presentation with or without proofs attached and returns a verificationResult in the response body.
      tags: 
       - Presentations
      operationId: verifyPresentation
      description: Verifies a verifiablePresentation and returns a verificationResult in the response body.  Given the possibility of denial of service, buffer overflow, or other style attacks, an implementation is permitted to rate limit or restrict requests against this API endpoint to those requests that contain only a single credential with a 413 or 429 error code as appropriate.
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/VerifyPresentationRequest"
                - $ref: "#/components/schemas/ProoflessVerifyPresentationRequest"
        description: Parameters for verifying a verifiablePresentation.
      responses:
        "200":
          description: Verifiable Presentation successfully verified!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyPresentationResponse"
        "400":
          description: Invalid or malformed input
        "401":
          description: Missing or invalid auth credentials.
        "403":
          description: Incorrect scope or permissions.
        "413":
          description: Payload too large
        "429":
          description: Request rate limit exceeded.
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    OAuth2:
      $ref: "./components/oauth2.yml#/components/securitySchemes/OAuth2"
  schemas:
    VerifyCredentialRequest:
      type: object
      properties:
        verifiableCredential:
          $ref: "./components/VerifiableCredential.yml#/components/schemas/VerifiableCredential"
        options:
          $ref: "./components/VerifyOptions.yml#/components/schemas/VerifyOptions"
    VerifyCredentialResponse:
      $ref: "./components/VerificationResult.yml#/components/schemas/VerificationResult"
    VerifyPresentationRequest:
      type: object
      properties:
        verifiablePresentation:
          $ref: "./components/VerifiablePresentation.yml#/components/schemas/VerifiablePresentation"
        options:
          $ref: "./components/VerifyOptions.yml#/components/schemas/VerifyOptions"
    ProoflessVerifyPresentationRequest:
      type: object
      properties:
        presentation:
          $ref: "./components/Presentation.yml#/components/schemas/Presentation"
    VerifyPresentationResponse:
      $ref: "./components/VerificationResult.yml#/components/schemas/VerificationResult"
